### ISSUE TITLE
Migrate knowledgebase "backend" from github discussions to proper markdown repo

### ISSUE THREAD

**Issue by rufuspollock** [comparethe/comparethe#2]
S: we started out just using github discussions https://github.com/orgs/comparethe/discussions

C: has several issues a) can't use obsidian or similar tools to manage content in github discussions (need markdown files in a repo for that) b) can't publish discussions to a website

H: let's move to a repo!

## Tasks

- [x] Create the repo **✅2024-12-09**
- [x] Publish with Flowershow **✅2024-12-09 https://flowershow.app/@rufuspollock/comparethe**
- [x] Set comparethe.org domain to that site **✅2024-12-09**
- [x] Stub the README to have useful content **✅2024-12-09 copied over content from github root page that was already developed**
- [x] #6
- [x] Add the habit stuff as a first try-out **✅2024-12-09 https://comparethe.org/Habit+tracking+apps**

Discussion migration

- [x] Setup discussions on comparethe
- [x] #7
- [x] Set comparethe discussions as default ...

### Extras

- [ ] #26

**Comment by rufuspollock** [comment]
![image](https://github.com/user-attachments/assets/d60d80d8-87bf-43d2-ab43-07aab313b85e)

**Comment by rufuspollock** [comment]
FIXED. Everything done except analytics which is blocked atm.
